---
title: "CellChat"
authors : "Flavie BERNIGOLE"
output: html_document
encoding: UTF-8
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Analyse des donnees: analyse des communication cellule-cellule (CellChat)

```{r}
# Chargement des librairies
library(umap)
#install.packages("rmazkdown")
library(rmarkdown)
#install.packages("YAML")
library(yaml)
library(ggalluvial)
library(NMF)
library(circlize)
library(ComplexHeatmap)
library(SummarizedExperiment)
library(SingleCellExperiment)
library(BiocGenerics)
library(MatrixGenerics)
library(DelayedArray)
library(S4Vectors)
library(Biobase)
library(BiocParallel)
library(BiocNeighbors)
library(circlize)
library(ggplot2)
library(reshape2)
library(Rtsne)
library(dplyr)
library(Seurat)
library(rlang)
library(glue)
library(Rcpp)
library(CellChat)
library(patchwork)
library(openxlsx)
options(StringsAsFactors = FALSE)
```

##Partie 1: Saisie et traitement des donn?es et initialisation de CellChat objet

```{r}
# Chargement des donnees
objet_seurat<-readRDS("~/EP2C/ObjetSeqwell/Annotation_v3/VPLI_152926_STARsolo_Round3Tier1_optimized.rds")

#Selection des données par stade + Enlever les Fibroblastes pour deuxième visualisation
VIR<- subset(objet_seurat, dvpmt.stage=="Virgin")
#VIR<- subset(VIR, subset = Annotation != "Fibroblasts")

PRE<- subset(objet_seurat, dvpmt.stage == "Pregnant")
#PRE<- subset(PRE, subset = Annotation != "Fibroblasts")

LACT<- subset(objet_seurat, dvpmt.stage == "Lactation")
#LACT<- subset(LACT, subset = Annotation != "Fibroblasts")

INV<- subset(objet_seurat, dvpmt.stage == "Involution")
#INV<- subset(INV, subset = Annotation != "Fibroblasts")

```

```{r}
#Création de l'object CellChat
CellchatSW <- createCellChat(object = INV, group.by = "Annotation")

#Mise en place de la base de donnees de la souris
CellChatDB <- CellChatDB.mouse
showDatabaseCategory(CellChatDB)
dplyr::glimpse(CellChatDB$interaction)
CellchatSW@DB <- CellChatDB

#Pr?traitement des donn?es
CellchatSW <- subsetData(CellchatSW)
CellchatSW <- identifyOverExpressedGenes(CellchatSW)
CellchatSW <- identifyOverExpressedInteractions(CellchatSW)
```

## Partie 2: Inf?rence d'un r?seau de communication de cellule ? cellule
```{r}
#Calcul de la probabilit? de communication et d?duction donn?es cellulaires: R?seau de communication
CellchatSW <- computeCommunProb(CellchatSW, type="triMean") #(+15min)
CellchatSW <- filterCommunication(CellchatSW, min.cells = 0)

#Extraction du r?seau de communication cellulaire
df.net <- subsetCommunication(CellchatSW)
write.xlsx(df.net, "~/EP2C/ObjetSeqwell/CellChat2/LACT/Ligand_R_SeqWell_LACT_sansfibro.xlsx")

#D?duire la communication cellule-cellule au niveau de la voie de signalisation
CellchatSW <- computeCommunProbPathway(CellchatSW)
                                        
#Calcul du r?seau de communication cellule par cellule
CellchatSW <- aggregateNet(CellchatSW)
saveRDS(CellchatSW, file = "~/EP2C/ObjetSeqwell/CellChat2/LACT/ObjetCellChatLACT_sansfibro.rds")


# Extraire la matrice de comptage des interactions
interaction_count_matrix <- CellchatSW@net$count
interaction_count_df <- as.data.frame(as.table(interaction_count_matrix))
print(interaction_count_df)
write.csv(interaction_count_df, file = "~/EP2C/ObjetSeqwell/CellChat2/LACT/interaction_count_LACT_sansfibro.csv", row.names = FALSE)
```

```{r,,fig.height=12}

#Visualisation de la communication en globalit?
groupSize <- as.numeric(table(CellchatSW@idents))
par(mfrow = c(1,2), xpd=TRUE)
netVisual_circle(CellchatSW@net$count, vertex.weight = groupSize, weight.scale = T, label.edge= F, title.name = "Number of interactions")
netVisual_circle(CellchatSW@net$weight, vertex.weight = groupSize, weight.scale = T, label.edge= F, title.name = "Interaction weights/strength")

```


```{r, fig.width=10}
#Visualisation de la communication cellule-cellule sous forme de heatmap
par(mfrow=c(1,1))
netVisual_heatmap(CellchatSW,color.heatmap = "Reds")

```
